chore: try to fail job before cancelling itself
this introduces race conditions but there is apparently no native way to do this for the gh api

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,7 +31,9 @@ jobs:
       - if: failure()
         env:
           GH_TOKEN: ${{ github.token }}
-        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
+        run: |
+          gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
+          exit 1 # try to fail fast before cancelling itself for better display in github
 
   typecheck:
     runs-on: ubuntu-24.04
@@ -51,7 +53,9 @@ jobs:
       - if: failure()
         env:
           GH_TOKEN: ${{ github.token }}
-        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
+        run: |
+          gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
+          exit 1 # try to fail fast before cancelling itself for better display in github
 
   lint:
     runs-on: ubuntu-24.04
@@ -71,7 +75,9 @@ jobs:
       - if: failure()
         env:
           GH_TOKEN: ${{ github.token }}
-        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
+        run: |
+          gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
+          exit 1 # try to fail fast before cancelling itself for better display in github
 
   format:
     runs-on: ubuntu-24.04
@@ -91,7 +97,9 @@ jobs:
       - if: failure()
         env:
           GH_TOKEN: ${{ github.token }}
-        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
+        run: |
+          gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
+          exit 1 # try to fail fast before cancelling itself for better display in github
 
   test:
     runs-on: ubuntu-24.04
@@ -111,7 +119,9 @@ jobs:
       - if: failure()
         env:
           GH_TOKEN: ${{ github.token }}
-        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
+        run: |
+          gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
+          exit 1 # try to fail fast before cancelling itself for better display in github
 
   test-e2e:
     runs-on: ubuntu-24.04
@@ -140,7 +150,9 @@ jobs:
       - if: failure()
         env:
           GH_TOKEN: ${{ github.token }}
-        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
+        run: |
+          gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
+          exit 1 # try to fail fast before cancelling itself for better display in github
 
   deploy:
     needs: [build, typecheck, lint, format, test, test-e2e]
